const loader = `(()=>{'use strict';if(window.InsightKMWidget)return;const instances=new Map();function init(options){if(!options||!options.botId||!options.apiBase||!options.hostOrigin)throw new Error('InsightKMWidget: botId, apiBase and hostOrigin are required');const apiBase=new URL(options.apiBase).origin;const hostOrigin=new URL(options.hostOrigin).origin;if(hostOrigin!==window.location.origin)throw new Error('InsightKMWidget: hostOrigin must match the current page');if(instances.has(options.botId))return instances.get(options.botId);const host=document.createElement('div');host.dataset.insightkmWidget=options.botId;document.body.appendChild(host);const root=host.attachShadow({mode:'open'});const position=options.position==='bottom-left'?'left:20px':'right:20px';const accent=options.theme==='slate'?'#0f172a':options.theme==='emerald'?'#047857':'#4f46e5';root.innerHTML='<style>:host{all:initial}.toggle{position:fixed;bottom:20px;'+position+';z-index:2147483000;display:grid;place-items:center;width:56px;height:56px;border:0;border-radius:50%;background:'+accent+';color:#fff;box-shadow:0 12px 30px #0f172a38;font:700 22px system-ui;cursor:pointer}.panel{position:fixed;bottom:88px;'+position+';z-index:2147482999;width:min(390px,calc(100vw - 24px));height:min(650px,calc(100dvh - 112px));border:0;border-radius:18px;background:#fff;box-shadow:0 18px 60px #0f172a45}.panel[hidden]{display:none}@media(max-width:520px){.panel{inset:0;width:100vw;height:100dvh;border-radius:0}.toggle{bottom:14px;'+(options.position==='bottom-left'?'left:14px':'right:14px')+'}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}</style><button class="toggle" aria-label="Open InsightKM chat" aria-expanded="false">✦</button><iframe class="panel" title="InsightKM secure chat" hidden></iframe>';const button=root.querySelector('.toggle'),frame=root.querySelector('.panel');frame.src=apiBase+'/api/embed/frame/'+encodeURIComponent(options.botId);let ready=false;function send(){if(!ready)return;frame.contentWindow.postMessage({type:'insightkm:init',botId:options.botId,hostOrigin,payload:options.payload,signature:options.signature,token:options.token},apiBase)}function open(){frame.hidden=false;button.setAttribute('aria-expanded','true');button.setAttribute('aria-label','Close InsightKM chat');send();frame.focus()}function close(){frame.hidden=true;button.setAttribute('aria-expanded','false');button.setAttribute('aria-label','Open InsightKM chat');button.focus()}button.addEventListener('click',()=>frame.hidden?open():close());window.addEventListener('message',event=>{if(event.origin!==apiBase||event.source!==frame.contentWindow||!event.data||event.data.botId!==options.botId)return;if(event.data.type==='insightkm:ready'){ready=true;send()}if(event.data.type==='insightkm:close')close()});const instance={open,close,destroy(){host.remove();instances.delete(options.botId)}};instances.set(options.botId,instance);return instance}window.InsightKMWidget={init}})();`;

export async function GET() {
  return new Response(loader, {
    headers: {
      "content-type": "application/javascript; charset=utf-8",
      "cache-control": "public, max-age=300",
      "access-control-allow-origin": "*",
      "cross-origin-resource-policy": "cross-origin",
      "x-content-type-options": "nosniff",
    },
  });
}
